version: '3'
services:
  trader-nginx:
    image: nginx:latest
    volumes:
      - ./images/nginx:/etc/nginx/conf.d
      - ../trader-site:/var/www/app
      - ./logs/nginx:/var/log/nginx
    depends_on:
      - trader-site
      - trader-postgres
    ports:
      - "84:80"
    networks:
      - trader

  trader-site:
    build: ./images/php
    container_name: trader-site
    depends_on:
      - trader-postgres
    volumes:
      - ../trader-site:/var/www/app
      - ./images/php/custom_php.ini:/usr/local/etc/php/conf.d/custom_php.ini
    networks:
      - trader

  trader-postgres:
    image: postgres:14.2-alpine
    environment:
      POSTGRES_USER: dbuser
      POSTGRES_PASSWORD: HCK6LrwUsVu63ZdF
      POSTGRES_DB: trader_db
    expose:
      - "5436"
    ports:
      - "5436:5436" # HOST:CONTAINER
    command: -p 5436
    volumes:
      # Database volume
      - ../data/postgres/pg_data:/var/lib/postgresql/data
      # Temp volume to allow using dumps
      - ../data/postgres/dumps:/tmp/
    networks:
      - trader

#  trader-go:
#    build:
#      context: ../
#      dockerfile: ./go-trader/docker/Dockerfile
#    volumes:
#      - ./logs/go-trader:/opt/app/logs
#    ports:
#      - "5244:5244"
#    networks:
#      - trader

  trader-adminer:
    image: adminer
    ports:
      - "8338:8080"
    networks:
      - trader

  trader-redis:
    image: redis
    volumes:
      - ./data/redis/data:/data
    ports:
      - "6379:6379"
    networks:
      - trader

networks:
  trader: